### UC9: Get all matches
GET http://localhost:8080/match
Accept: application/json

### UC10: Get a specific match
GET http://localhost:8080/match/1
Accept: application/json

### UC1: Admin adds new data to database
POST http://localhost:8080/match
Content-Type: application/json

{
  "homeTeam": "Víkingur Ólafsvík",
  "awayTeam": "KR",
  "homeScore": 2,
  "awayScore": 1,
  "matchDate": "2024-08-10"
}
